name: Bug Report
description: Create a report to help us improve.
title: "[BUG]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear description of what the bug is.
      placeholder: "Tell us what you see"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: "How can we reproduce the issue?"
      value: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: "A clear description of what actually happened."
    validations:
      required: true