source 'https://rubygems.org/'

gem 'puma'
gem 'sinatra'
gem "rackup", "~> 2.2"

gem "prometheus-client"

gem 'erb'
gem 'httparty'
gem 'sinatra-flash'

gem 'bcrypt' # for hashing the user passwords
gem 'dotenv'
gem 'sqlite3'

gem 'rack-test'
gem 'rubocop'
gem 'test-unit'