source 'https://rubygems.org/'

gem 'sinatra'
gem 'puma'
gem "rackup", "~> 2.2"

gem 'httparty'
gem 'erb'
gem 'sinatra-flash'

gem 'sqlite3'
gem 'bcrypt' # for hashing the user passwords
gem 'dotenv'

gem 'test-unit'
gem 'rack-test'
gem 'rubocop'
gem "prometheus-client"